@api = http://localhost:3001/api/general/brand

###
GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "name":"BIXOLON",
  "userId":"1726789025"
}

###
GET {{api}}/2

###
PUT {{api}}/2
Content-Type: application/json

{
  "name":"ASUS",
  "userId":"1002290987"
}

###
DELETE {{api}}/3

