@api = http://localhost:3001/api/computer/ram

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "description":"16GB - DDR3",
  "userId":"1726789025"
}

###
GET {{api}}/2

###
PUT {{api}}/2
Content-Type: application/json

{
  "description":"prueba 3",
  "userId":"1002290987"
}

###
DELETE {{api}}/2