@api = http://localhost:3001/api/printer/place

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "name":"prueba",
  "supervisorId":1,
  "userId":"1726789025"
}

###
GET {{api}}/4

###
PUT {{api}}/4
Content-Type: application/json

{
  "name":"prueba 3",
  "supervisorId":1,
  "userId":"1002290987"
}

###
DELETE {{api}}/4