@api = http://localhost:3001/api/printer/image

GET {{api}}?printerId=10

###
POST {{api}}
Content-Type: application/json

{
  "name":"prueba5.pdf",
  "printerId":10,
  "userId":"1726789025"
}

###
GET {{api}}/2

###
DELETE {{api}}/4